FROM python:3.9-slim
LABEL Author="Kevin Buffardi"
LABEL version="0.1"
LABEL name="codewitus-python"
WORKDIR /usr/src
COPY code.py .
COPY testfile.py .
RUN pip install unittest-xml-reporting
RUN python -m py_compile code.py
CMD ["python", "testfile.py"]

